AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageBucketName:
    Default: imgs.networkchallenge.de
    Type: String
    MinLength: 1

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./deploy/api.yaml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref ResizeFunction

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ImageBucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        RoutingRules:
          - RedirectRule:
              HttpRedirectCode: 307
              HostName: !Sub ${Api}.execute-api.${AWS::Region}.amazonaws.com
              Protocol: https
              ReplaceKeyPrefixWith: prod?key=
            RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: 404

  ResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/function.zip
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 256
      Timeout: 20
      Environment:
        Variables:
          BUCKET: !Ref ImageBucket
          URL: !Join
            - ''
            - - 'https://'
              - !Ref ImageBucketName
      Policies:
          Statement:
            - Resource: !Sub arn:aws:s3:::${ImageBucket}/*
              Effect: Allow
              Action:
                - s3:PutObject

  ResizeFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResizeFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*

  ImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImageBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource: !Sub arn:aws:s3:::${ImageBucket}/*
  S3UploadPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowUserToSeeBucketListInTheConsole
            Action:
              - 's3:ListAllMyBuckets'
            Effect: Allow
            Resource: '*'
          - Sid: AllowUserAllS3Actions
            Action: 's3:*'
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${ImageBucket}
              - !Sub arn:aws:s3:::${ImageBucket}/*
      PolicyName: S3ImageUpload
      Users:
        - !Ref UserImgUpload
  UserImgUpload:
    Type: AWS::IAM::User
    Properties:
      UserName: cfn-generic-img-uploader
Outputs:
  BucketWebsiteUrl:
    Value: !GetAtt ImageBucket.WebsiteURL
  Bucket:
    Value: !Ref ImageBucket
