AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageBucketName:
    Default: imgs.networkchallenge.de
    Type: String
    MinLength: 1

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./deploy/api.yaml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref ResizeFunction

  ImageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref ImageBucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        RoutingRules:
          - RedirectRule:
              HttpRedirectCode: 307
              HostName: !Sub ${Api}.execute-api.${AWS::Region}.amazonaws.com
              Protocol: https
              ReplaceKeyPrefixWith: prod?key=
            RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: 404

  ResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/function.zip
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 256
      Timeout: 20
      Environment:
        Variables:
          BUCKET: !Ref ImageBucket
          URL: !GetAtt ImageBucket.WebsiteURL
      Policies:
          Statement:
            - Resource: !Sub arn:aws:s3:::${ImageBucket}/*
              Effect: Allow
              Action:
                - s3:PutObject

  ResizeFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResizeFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*

  ImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImageBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource: !Sub arn:aws:s3:::${ImageBucket}/*
  ApexCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref ImageBucketName
        Enabled: True
        Origins:
          - DomainName: !Select
              - 1
              - !Split ["//", !GetAtt ImageBucket.WebsiteURL]
            Id: origin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: origin
          DefaultTTL: 5
          MaxTTL: 30
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:301713784098:certificate/464ae195-cb39-4c00-bbc3-ad5bf869f69e
          SslSupportMethod: sni-only
Outputs:
  BucketWebsiteUrl:
    Value: !GetAtt ImageBucket.WebsiteURL
  Bucket:
    Value: !Ref ImageBucket
  ApexCloudFrontDomain:
    Description: >-
      The CloudFront domain name for the Apex
      domain that we can use to add a CNAME to
      later.
    Value: !GetAtt ApexCloudFront.DomainName
