AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
    Default: nc-infrastructure

Resources:
  InfraBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      
  InfraBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref InfraBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource: !Sub arn:aws:s3:::${InfraBucket}/*

Outputs:
  Bucket:
    Value: !Ref InfraBucket
    Export:
      Name: !Sub ${AWS::StackName}-InfraBucket
